### ISSUE TITLE
Make it possible to send raw RSS feeds without the translations

### ISSUE THREAD

**Issue by dlampsi** [dlampsi/broadcaster#14]
Config entry example:
```yaml
feeds:
  - source: NY Times
    category: World
    url: https://rss.nytimes.com/services/xml/rss/nyt/World.xml
    language: en
    notify:
      - type: telegram
        chat_id: -1234567890
```
